O objetivo deste exercício é utilizar a base de dados do crédito e aplicar a técnica de seleção de atributos utilizando variância

Carregue o arquivo credit_data.csv

Calcule a variância para os atributos income, age e loan e aplique o método de seleção Low Variance

Faça um teste do accuracy utilizando o algoritmo Naïve Bayes, sem seleção de atributos e com seleção de atributos

Na próxima aula você pode assistir o vídeo com a solução

In [1]:
# librarys import
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import VarianceThreshold
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [2]:
# Import data set
df = pd.read_csv('credit_data.csv')
df.dropna(inplace = True)
df.head()

i#clientid        income        age         loan  c#default
0           1  66155.925095  59.017015  8106.532131          0
1           2  34415.153966  48.117153  6564.745018          0
2           3  57317.170063  63.108049  8020.953296          0
3           4  42709.534201  45.751972  6103.642260          0
4           5  66952.688845  18.584336  8770.099235          1

In [3]:
# View describe
df.describe()

i#clientid        income          age          loan    c#default
count  1997.000000   1997.000000  1997.000000   1997.000000  1997.000000
mean   1001.956935  45333.864334    40.807559   4445.487716     0.141713
std     576.702206  14325.131177    13.624469   3046.792457     0.348842
min       1.000000  20014.489470   -52.423280      1.377630     0.000000
25%     503.000000  32804.904487    28.990415   1936.813257     0.000000
50%    1002.000000  45788.747100    41.317159   3977.287432     0.000000
75%    1501.000000  57787.565659    52.587040   6440.861434     0.000000
max    2000.000000  69995.685578    63.971796  13766.051239     1.000000

In [4]:
# Calculando a variancia nos 3 campos
np.var(df['income']),np.var(df['age']), np.var(df['loan'])

(205106624.40660834, 185.53321543372624, 9278295.832931679)

In [5]:
# Separando x e y
x = df[['income','age','loan']].values
y = df['c#default']

In [6]:
# verificando valores em x
x

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [7]:
# Normalizacao dos dados
scaler = MinMaxScaler()
x = scaler.fit_transform(x)

In [8]:
# Verificando dados normalizados
x

array([[0.9231759 , 0.95743135, 0.58883739],
       [0.28812165, 0.86378597, 0.47682695],
       [0.74633429, 0.99257918, 0.58262011],
       ...,
       [0.48612202, 0.69109837, 0.40112895],
       [0.47500998, 1.        , 0.1177903 ],
       [0.98881367, 0.93282208, 0.53597028]])

In [9]:
# Calculando a menor variancia com os dados normalizados
min(np.var(x[0]),np.var(x[1]), np.var(x[2]))

0.027646353650092215

In [10]:
# retirando do dataset o parametro de menor variancia
separar = VarianceThreshold(threshold=0.027)
x_separado =  separar.fit_transform(x)
x_separado

array([[0.9231759 , 0.58883739],
       [0.28812165, 0.47682695],
       [0.74633429, 0.58262011],
       ...,
       [0.48612202, 0.40112895],
       [0.47500998, 0.1177903 ],
       [0.98881367, 0.53597028]])

In [11]:
# Treinando dois modelos (Com dataset completo, e com dataset sem a coluna de menor variancia)
naive_total = GaussianNB()
naive_separado = GaussianNB()

naive_total.fit(x,y)
naive_separado.fit(x_separado,y)

GaussianNB()

In [12]:
# Acuracia Dataset total
predict_total = naive_total.predict(x)
print('A Acuracia de um modelo treinado com todos os tres parametros,\nobteve resultado de: ',accuracy_score(y,predict_total))

A Acuracia de um modelo treinado com todos os tres parametros,
obteve resultado de:  0.9253880821231848


In [13]:
# Acuracia Dataset separado
predict_sep = naive_separado.predict(x_separado)
print('Acuracia do modelo treinado com dois parametros (age, loan) \na acuracia foi de: ',accuracy_score(y,predict_sep))

Acuracia do modelo treinado com dois parametros (age, loan) 
a acuracia foi de:  0.8472709063595393


## Conclusao

Observe que para este exemplo, o ideal e' permanecer com as tres variaveis, apesar de muitas vezes retirar os parametros que possuem menor variancia, resulta em um modelo mais bem treinado, quando os parametros sao poucos (neste caso 3 apenas) retirar um deles nao e' a melhor opcao.